### ISSUE TITLE
MAC to Windows Issue

### ISSUE THREAD

**Issue by DrDreGFunk** [deepfakes/faceswap-playground#119]
**Computer Specs**

Edition: Windows 10
Processor: Intel(R) Celeron(R) CPU N2840
Installed RAM: 4.00 GB (3.88 GB Usable)

**Intro**

Ok, so I heard that the actual FakeApp is better to use than doing it on a MAC so I imported all my data_A and data_B to my windows. They were already aligned. I managed to find my old windows 10 laptop so I could run the FakeApp app on it. I then followed this tutorial: https://www.deepfakes.club/tutorial/ 
I used the tutorial to get my laptop up and running with CUDA 8 and did all the stuff with the environment variables. 

![screenshot 4](https://user-images.githubusercontent.com/36054512/38117650-28132b78-33ae-11e8-8c01-360f30693308.png)

Because all my datasets were already aligned and I had the model as I initially did the training on the  MAC before. I just kept the folders as they were and put them in a newly created "Fakes" folder.

![fakes folder](https://user-images.githubusercontent.com/36054512/38117990-f322aa54-33af-11e8-8258-6e5edfc2bd6e.png)

In the FakeApp, I changed the file locations to these folders (as shown below).

![initially gpu](https://user-images.githubusercontent.com/36054512/38118036-2e894b70-33b0-11e8-9b37-80d21cbb3cfd.png)

*SWITCHING FROM GPU TO CPU IN FAKEAPP*

![to cpu](https://user-images.githubusercontent.com/36054512/38118039-30913388-33b0-11e8-9e35-61cd6638db26.png)

TERMINAL ERROR IN WINDOWS:
------------------------------------------------------------------------------------------------------

`Using CPU for processing
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 172, in __init__
  File "ctypes\__init__.py", line 351, in __init__
OSError: [WinError 126] The specified module could not be found`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "site-packages\tensorflow\python\platform\self_check.py", line 62, in preload_check
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 174, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'nvcuda.dll'. Most probably this dynlib/dll was not found when the application was frozen.`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "train.py", line 40, in <module>
  File "d:\anaconda\envs\merging\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "model.py", line 12, in <module>
  File "d:\anaconda\envs\merging\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\tensorflow\__init__.py", line 24, in <module>
  File "d:\anaconda\envs\merging\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\tensorflow\python\__init__.py", line 49, in <module>
  File "d:\anaconda\envs\merging\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
  File "site-packages\tensorflow\python\platform\self_check.py", line 70, in preload_check
ImportError: Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.
[6020] Failed to execute script train`

------------------------------------------------------------------------------------------------------

I think it's still using GPU even though I want to use CPU. How do you change that? (if that is the problem)???.

**Comment by bryanlyon** [comment]
We are not part of the group who make the fakeapp GUI.  Right now, there is no way to specify if you are using GPU or CPU except during install.  You have installed the GPU version of the tensorflow which will not work without the GPU.  To get this to work you'll probably want to uninstall everything then follow our steps to install the CPU only version without the GUI.  You can try to uninstall just tensorflow and then install the CPU version, but people have had trouble making the switch between CPU and GPU versions without problems.

**Comment by Kirin-kun** [comment]
And btw, FakeApp isn't a gui for faceswap as some people seem to think. I think it used some of the code of dfaker or here, but it was customized afterward.

Anyway, you do have CUDA installed, so I guess you have an NVidia GPU, unless you forced the install, because if it doesn't detect an nvidia, it warns you at install time. 

But you're talking about an "old laptop" so I'm dubious about what adapter you're using.
