### ISSUE TITLE
Error：_tkinter.TclError: couldn't recognize data in image file "....deepfakes-faceswap/icons/open_folder.png"

### ISSUE THREAD

**Issue by theoldgun** [deepfakes/faceswap-playground#138]
I have the problem,please help me:
(faceswap_env) dms@dms-System-Product-Name:~/cuifengyi-work/deepfakes-faceswap$ python faceswap.py -h
Traceback (most recent call last):
  File "faceswap.py", line 30, in <module>
    subparser, guiparsers, "gui", "Launch the Faceswap Graphical User Interface.")
  File "/home/dms/cuifengyi-work/deepfakes-faceswap/scripts/gui.py", line 1104, in __init__
    self.root = FaceswapGui(self.utils, calling_file=cmd[0])
  File "/home/dms/cuifengyi-work/deepfakes-faceswap/scripts/gui.py", line 363, in __init__
    self.utils.init_tk()
  File "/home/dms/cuifengyi-work/deepfakes-faceswap/scripts/gui.py", line 73, in init_tk
    file=os.path.join(pathicons, 'open_folder.png'))
  File "/home/dms/anaconda3/lib/python3.5/tkinter/__init__.py", line 3394, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/home/dms/anaconda3/lib/python3.5/tkinter/__init__.py", line 3350, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/home/dms/cuifengyi-work/deepfakes-faceswap/icons/open_folder.png"

## Other relevant information
- **Operating system and version:ubuntu 16.04
- **Python version: 3.5.2
- **Faceswap method:GPU 1060

**Comment by torzdf** [comment]
Does the file 

`/home/dms/cuifengyi-work/deepfakes-faceswap/icons/open_folder.png `

exist?

Can you open it outside of faceswap?

Has it got the correct permissions?

**Comment by theoldgun** [comment]
yes，it exist.
I have solved the problem,thank you @torzdf !!~~~

**Comment by spicalous** [comment]
@theoldgun How did you fix this issue?
