### ISSUE TITLE
ImportError: DLL load failed: Unable to find the specified module

### ISSUE THREAD

**Issue by JobSmith** [deepfakes/faceswap-playground#154]
All the dependency I've installed, but when I tried this command:

```
(dpenv) E:\python\ml\project\faceswap>python faceswap.py extract
Traceback (most recent call last):
  File "faceswap.py", line 32, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "E:\python\ml\project\faceswap\lib\cli.py", line 35, in execute_script
    script = self.import_script()
  File "E:\python\ml\project\faceswap\lib\cli.py", line 22, in import_script
    from scripts.extract import Extract as script
  File "E:\python\ml\project\faceswap\scripts\extract.py", line 10, in <module>
    from scripts.fsmedia import Alignments, Faces, Images, Utils
  File "E:\python\ml\project\faceswap\scripts\fsmedia.py", line 16, in <module>
    from lib.faces_detect import detect_faces, DetectedFace
  File "E:\python\ml\project\faceswap\lib\faces_detect.py", line 1, in <module>
    from lib import FaceLandmarksExtractor
  File "E:\python\ml\project\faceswap\lib\FaceLandmarksExtractor\__init__.py", line 1, in <module>
    from .FaceLandmarksExtractor import extract
  File "E:\python\ml\project\faceswap\lib\FaceLandmarksExtractor\FaceLandmarksExtractor.py", line 5, in <module>
    import dlib
ImportError: DLL load failed: 找不到指定的模块。
```

**Comment by Kirin-kun** [comment]
Your dlib module isn't properly installed/compiled.

**Comment by JobSmith** [comment]
```

(dpenv) E:\python\ml\project\faceswap>pip freeze
absl-py==0.2.0
bleach==1.5.0
certifi==2018.4.16
click==6.7
cycler==0.10.0
Cython==0.28.2
decorator==4.3.0
dlib==19.10.99
face-recognition==1.2.2
face-recognition-models==0.3.0
h5py==2.7.1
html5lib==0.9999999
Keras==2.1.2
kiwisolver==1.0.1
Markdown==2.6.11
matplotlib==2.2.2
mkl-fft==1.0.0
mkl-random==1.0.1
networkx==2.1
numpy==1.14.2
opencv-python==3.3.0.10
pathlib==1.0.1
Pillow==5.1.0
protobuf==3.5.2.post1
pyparsing==2.2.0
python-dateutil==2.7.2
pytz==2018.4
PyWavelets==0.5.2
PyYAML==3.12
scandir==1.6
scikit-image==0.13.1
scipy==1.0.1
six==1.11.0
tensorflow==1.5.0
tensorflow-gpu==1.5.0
tensorflow-tensorboard==1.5.1
tqdm==4.23.2
Werkzeug==0.14.1
wincertstore==0.2
```

**Comment by Kirin-kun** [comment]
Did you install the Visual C++ 2015 redistributable?
Did you install cuDNN 7?

**Comment by JobSmith** [comment]
My env path is located at:

```
D:\Anaconda\envs\dfenv
```

And my faceswap project and dlib is located at:

![image](https://user-images.githubusercontent.com/15700681/39563817-3caa78ba-4ee4-11e8-894a-d918cb10f333.png)

**Comment by JobSmith** [comment]
Yes, I installed it!

**Comment by JobSmith** [comment]
Do you means this PATH:

![image](https://user-images.githubusercontent.com/15700681/39564367-8739b204-4ee6-11e8-9c8f-c952261a06b0.png)

![image](https://user-images.githubusercontent.com/15700681/39564406-aadc5e96-4ee6-11e8-80d9-a987c2226e79.png)

**Comment by Kirin-kun** [comment]
It doesn't look like your problem is specific to faceswap, but specific to your installation. Something is wrong/missing. The VC++ redistributable is the most likely candidate.

Just launch a python interpreter and type "import dlib" ?

Also, can you recompile dlib and show any error?

You pull the latest dlib from github and do a "python setup.py build"

**Comment by JobSmith** [comment]
I just downloaded the latest dlib from https://github.com/davisking/dlib

![image](https://user-images.githubusercontent.com/15700681/39565388-52468a78-4eea-11e8-8824-ab9cf57f6205.png)

![image](https://user-images.githubusercontent.com/15700681/39565663-66362a42-4eeb-11e8-8c25-28814d343971.png)

And  I have been rebuilding dlib.
It takes time.
I will show it when it finished.

**Comment by JobSmith** [comment]
Oh, my god! When I restarted my PC, this error disappeared!
