### ISSUE TITLE
Error for python faceswap.py gui 

### ISSUE THREAD

**Issue by michaelzhang917** [deepfakes/faceswap-playground#175]
I got the following error for running python faceswap.py gui

Did anyone know how to solve it?

Traceback (most recent call last):
  File "faceswap.py", line 33, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "/home/colin-ai/faceswap/lib/cli.py", line 38, in execute_script
    process = script(*args)
  File "/home/colin-ai/faceswap/scripts/gui.py", line 1197, in __init__
    self.root = FaceswapGui(self.utils, calling_file=cmd[0])
  File "/home/colin-ai/faceswap/scripts/gui.py", line 370, in __init__
    self.utils.init_tk()
  File "/home/colin-ai/faceswap/scripts/gui.py", line 76, in init_tk
    file=os.path.join(pathicons, 'open_folder.png'))
  File "/home/colin-ai/anaconda3/lib/python3.6/tkinter/__init__.py", line 3539, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/home/colin-ai/anaconda3/lib/python3.6/tkinter/__init__.py", line 3495, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/home/colin-ai/faceswap/icons/open_folder.png"

**Comment by torzdf** [comment]
Is this from latest master branch? Check permissions on that folder

**Comment by michaelzhang917** [comment]
Yes, it is the latest and it works for other functions. Here is the information when I do ls
I don't see any wrong with the file.

colin-ai@colinai-X9DAi-Invalid-entry-length-16-Fixed-up-to-11:~/faceswap$ ls /home/colin-ai/faceswap/icons/open_folder.png -l
-rw-rw-r-- 1 colin-ai colin-ai 51965 Jun  3 16:52 /home/colin-ai/faceswap/icons/open_folder.png
