### ISSUE TITLE
convert.py: no image shape

### ISSUE THREAD

**Issue by agilebean** [deepfakes/faceswap-playground#187]
This is not a bug because I already had succesful conversions.
Rather this time, I used faces changed by neural style transfer.
So I need to understand the error message and how I can prevent it.

## Expected behavior
succesful conversion with convert.py

## Actual behavior
convert.py throws attribute error: model object has no attribute
```
Output Directory: /home/agilebean/faceswap/output
Input Directory: /home/agilebean/faceswap/input_images
Loading Extract from Extract_Align plugin...
Using json serializer
Alignments filepath: /home/agilebean/faceswap/input_images/alignments.json
Aligned directory not specified. All faces listed in the alignments file will be converted
Loading Model from Model_Original plugin...
loaded model weights
Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "/home/agilebean/faceswap/lib/cli.py", line 81, in execute_script
    process.process()
  File "/home/agilebean/faceswap/scripts/convert.py", line 42, in process
    model = self.load_model()
  File "/home/agilebean/faceswap/scripts/convert.py", line 74, in load_model
    self._image_shape = model.IMAGE_SHAPE
AttributeError: 'Model' object has no attribute 'IMAGE_SHAPE'
```

## Steps to reproduce

yes | python3 faceswap.py convert -i $INPUT_IMAGE_DIR -o $OUTPUT_IMAGE_DIR -m $MODEL_DIR -t $TRAINER

## Other relevant information
- **Operating system and version:** Ubuntu 16.04 LTS 
- **Python version:** 3.5
- **Faceswap version:** latest
- **Faceswap method:** GPU

**Comment by agilebean** [comment]
The error message doesn't appear any more with the latest releases.
I think you can close this issue now.
