### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'multiprocess'

### ISSUE THREAD

**Issue by RattleRabbit6** [deepfakes/faceswap-playground#200]
After training my model and trying to run the convert script on Ubuntu with CUDA 9.0, I keep getting the following error:

```
Using TensorFlow backend.
Output Directory: output
Input Directory: input
Loading Extract from Extract_Align plugin...
Using json serializer
Alignments filepath: input/alignments.json
Aligned directory not specified. All faces listed in the alignments file will be converted
Alignments file not found. Generating at default values...
Output Directory: output
Input Directory: input
Loading Extract from Extract_Align plugin...
Using json serializer
Alignments filepath: input/alignments.json
Starting, this may take a while...
Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "~/faceswap/lib/cli.py", line 81, in execute_script
    process.process()
  File "~/faceswap/scripts/convert.py", line 38, in process
    self.generate_alignments()
  File "~/faceswap/scripts/convert.py", line 60, in generate_alignments
    extract.process()
  File "~/faceswap/scripts/extract.py", line 36, in process
    if self.args.multiprocess and GPUStats().device_count == 0:
AttributeError: 'Namespace' object has no attribute 'multiprocess'
```

I'm just an end-user, but if I'm reading it right it seems like it's running on CPU? I checked to make sure tensorflow-gpu is recognizing my device and it is, and training went fine. What is causing this error? On a previous installation I was able to run the script without issue.

**Comment by gessyoo** [comment]
The GPU is used for training but I think conversion is CPU only.
What was your command line that generated this error?  I see the script is looking for the alignments.json file but not finding it:   
Aligned directory not specified. All faces listed in the alignments file will be converted
Alignments file not found. Generating at default values... 

Did you specify the alignment directory in the command line with the -a parameter?   Use python faceswap.py convert -h to see all the variables.   Try re-running pip install -r requirements.txt to make sure the required dependencies are installed.

**Comment by torzdf** [comment]
This is a bug. It is looking for multiprocess flag when running extract (because it can't find an alignments file). I'll look to raise a fix.

In the meantime, you can run extract on your datasource first, then perform the convert.

**Comment by RattleRabbit6** [comment]
Deeply appreciate your response, however your suggested solution didn't work. I tried running extract on my originals folder and while it supposedly ran successfully, it returned "faces detected: 0" when I subsequently tried to run convert again, I got the following:

```
Using TensorFlow backend.
Output Directory: output
Input Directory: input
Loading Extract from Extract_Align plugin...
Using json serializer
Alignments filepath: input/alignments.json
Aligned directory not specified. All faces listed in the alignments file will be converted
Loading Model from Model_Original plugin...
loaded model weights
Loading Convert from Convert_Masked plugin...
No alignment found for 000001.png, skipping
```
etc., etc., for every image.

**Comment by torzdf** [comment]
This is a different issue and most likely to do with your CUDA or DLIB setup.

**Comment by torzdf** [comment]
Actually, can you print you extract command and run it with the -v flag, then paste the output.

**Comment by RattleRabbit6** [comment]
```
Using TensorFlow backend.
Output Directory: output
Input Directory: input
Loading Extract from Extract_Align plugin...
Using json serializer
Alignments filepath: input/alignments.json
Starting, this may take a while...
Writing alignments to: input/alignments.json
-------------------------
Images found:        5132
Faces detected:      0
-------------------------
Done!

```
That's it.

**Comment by RattleRabbit6** [comment]
It is, that's all I get for some reason

**Comment by torzdf** [comment]
Could you also paste the full faceswap command you are running?

Are you using the latest version of the code? Verbose should output something like:
```

(faceenv) C:\Users\Kirin\face>python c:\users\kirin\faceswap\faceswap.py extract
 -i H:\Fakes\lili -o H:\Fakes\lili\aligned.dlib-cnn -D dlib-cnn -r on -ae -v
Using TensorFlow backend.
Output Directory: H:\Fakes\lili\aligned.dlib-cnn
Input Directory: H:\Fakes\lili
Loading Extract from Extract_Align plugin...
Using json serializer
Alignments filepath: H:\Fakes\lili\alignments.json
Starting, this may take a while...
  0%|                                                    | 0/1 [00:00<?, ?it/s]
----- Initial GPU Stats -----
GPU Driver:       398.36
GPU Device count: 1
GPU Devices:      ['GeForce GTX 1060 6GB']
GPU VRAM:         [6144.0]
GPU VRAM free:    6026.6875
-----------------------------

Initializing keras model...
2018-07-07 20:18:31.132680: I T:\src\github\tensorflow\tensorflow\core\common_ru
ntime\gpu\gpu_device.cc:1356] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 5.78GiB
2018-07-07 20:18:31.141680: I T:\src\github\tensorflow\tensorflow\core\common_ru
ntime\gpu\gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-07 20:18:31.749715: I T:\src\github\tensorflow\tensorflow\core\common_ru
ntime\gpu\gpu_device.cc:923] Device interconnect StreamExecutor with strength 1
edge matrix:
2018-07-07 20:18:31.756716: I T:\src\github\tensorflow\tensorflow\core\common_ru
ntime\gpu\gpu_device.cc:929]      0
2018-07-07 20:18:31.759716: I T:\src\github\tensorflow\tensorflow\core\common_ru
ntime\gpu\gpu_device.cc:942] 0:   N
2018-07-07 20:18:31.763716: I T:\src\github\tensorflow\tensorflow\core\common_ru
ntime\gpu\gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:
0/task:0/device:GPU:0 with 2304 MB memory) -> physical GPU (device: 0, name: GeF
orce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Adding DLib - CNN detector
GPU VRAM free:    3433.41796875
Warning: No faces were detected.
Failed to extract from image: H:\Fakes\lili\test.png. Reason: Error while callin
g cudaMalloc(&data, n) in file C:\Users\Kirin\AppData\Local\Temp\pip-install-08l
oid12\dlib\dlib\cuda\cuda_data_ptr.cpp:28. code: 2, reason: out of memory
100%|████████████████████████████████████████████| 1/1 [00:17<00:00, 17.99s/it]
Writing alignments to: H:\Fakes\lili\alignments.json
-------------------------
Images found:        1
Faces detected:      0
-------------------------
Done!
```

**Comment by RattleRabbit6** [comment]
I'm just using the default settings, the command is simply
`python faceswap.py extract -v`
But it just doesn't produce the verbose output. It does with convert.

**Comment by RattleRabbit6** [comment]
I simply reinstalled and extract is functioning again.

**Comment by torzdf** [comment]
@RattleRabbit6 for original issue, please check latest commit in staging branch
