### ISSUE TITLE
AttributeError: module 'keras.engine' has no attribute 'base_layer'

### ISSUE THREAD

**Issue by ruah1984** [deepfakes/faceswap-playground#201]
Found this issue, may i know why ?? 

C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
File "C:\Users\ruah1\Downloads\faceswap-master\faceswap-master\faceswap.py", line 36, in <module>
ARGUMENTS.func(ARGUMENTS)
File "C:\Users\ruah1\Downloads\faceswap-master\faceswap-master\lib\cli.py", line 79, in execute_script
script = self.import_script()
File "C:\Users\ruah1\Downloads\faceswap-master\faceswap-master\lib\cli.py", line 28, in import_script
module = import_module(mod)
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "C:\Users\ruah1\Downloads\faceswap-master\faceswap-master\scripts\extract.py", line 12, in <module>
from scripts.fsmedia import Alignments, Faces, Images, Utils
File "C:\Users\ruah1\Downloads\faceswap-master\faceswap-master\scripts\fsmedia.py", line 16, in <module>
from lib.faces_detect import detect_faces, DetectedFace
File "C:\Users\ruah1\Downloads\faceswap-master\faceswap-master\lib\faces_detect.py", line 4, in <module>
from lib import face_alignment
File "C:\Users\ruah1\Downloads\faceswap-master\faceswap-master\lib\face_alignment\__init__.py", line 1, in <module>
from .extractor import Extract
File "C:\Users\ruah1\Downloads\faceswap-master\faceswap-master\lib\face_alignment\extractor.py", line 12, in <module>
from .model import KerasModel
File "C:\Users\ruah1\Downloads\faceswap-master\faceswap-master\lib\face_alignment\model.py", line 13, in <module>
class TorchBatchNorm2D(keras.engine.base_layer.Layer):
AttributeError: module 'keras.engine' has no attribute 'base_layer'

**Comment by torzdf** [comment]
Upgrade keras to 2.2.0
