### ISSUE TITLE
Possible conflicts with Keras 2.2.0 and 2.2.2

### ISSUE THREAD

**Issue by richard-bmc** [deepfakes/faceswap-playground#202]
## Expected behavior
The version of keras is 2.2.0. I use the following command to train:
```
python faceswap.py train -A path _to_A -B path_to_B -m path_to_model -t GAN128 -g 1 -pl -v
```
And the error message says the module "keras_vggface" cannot be found:
```
  File "c:\python36_64\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\python36_64\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Projects\DeepFakes\faceswap\scripts\train.py", line 97, in process_thread
    raise err
  File "c:\Projects\DeepFakes\faceswap\scripts\train.py", line 87, in process_thread
    trainer = self.load_trainer(model)
  File "c:\Projects\DeepFakes\faceswap\scripts\train.py", line 116, in load_trainer
    self.args.perceptual_loss)
  File "c:\Projects\DeepFakes\faceswap\plugins\Model_GAN128\Trainer.py", line 50, in __init__
    self.setup()
  File "c:\Projects\DeepFakes\faceswap\plugins\Model_GAN128\Trainer.py", line 66, in setup
    from keras_vggface.vggface import VGGFace
ModuleNotFoundError: No module named 'keras_vggface'
```
Then I upgrade keras to 2.2.2, the error message becomes:
```
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Projects\faceswap\scripts\train.py", line 97, in process_thread
    raise err
  File "C:\Projects\faceswap\scripts\train.py", line 86, in process_thread
    model = self.load_model()
  File "C:\Projects\faceswap\scripts\train.py", line 102, in load_model
    model = PluginLoader.get_model(self.trainer_name)(model_dir, self.args.gpus)
  File "C:\Projects\faceswap\plugins\Model_GAN128\Model.py", line 56, in __init__
    self.netGA, self.netGB = self.build_generator()
  File "C:\Projects\faceswap\plugins\Model_GAN128\Model.py", line 125, in build_generator
    encoder = Encoder()
  File "C:\Projects\faceswap\plugins\Model_GAN128\Model.py", line 102, in Encoder
    out = upscale_ps(512)(x)
  File "C:\Projects\faceswap\plugins\Model_GAN128\Model.py", line 87, in block
    x = PixelShuffler()(x)
  File "C:\Projects\faceswap\lib\PixelShuffler.py", line 13, in __init__
    self.data_format = conv_utils.normalize_data_format(data_format)
AttributeError: module 'keras.utils.conv_utils' has no attribute 'normalize_data_format'
```
According to [this post](https://github.com/keras-team/keras/commit/d40656e5799dfd22e96b8bab217638b2934a6894#diff-bd2e0f40db92ce410890f59d7d79712f), 'normalize_data_format' has been moved to somewhere else.

## Other relevant information
- **Operating system and version:** Windows 7
- **Python version:** 3.6.6
- **Faceswap version:** 163942f

**Comment by torzdf** [comment]
`pip install pip keras_vggface`

**Comment by richard-bmc** [comment]
@torzdf Installing keras_vggface solved my problem. Thank you!
