### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by maxsmith2300** [deepfakes/faceswap-playground#222]
## Expected behavior

Trying to my first train via the GUI and getting the below error

## Steps to reproduce

Extracted two set of images (look all good) and started the training process

## Other relevant information

Command: 
C:\Users\####\Anaconda3\envs\faceswap\python.exe C:\Users\####\Downloads\faceswap-master\faceswap-master\faceswap.py train -A E:\9c1d139d-09a4-452e-87fd-95f81ac5d711\arc\dfv\K1\s\Output -B E:\9c1d139d-09a4-452e-87fd-95f81ac5d711\arc\dfv\K1\v\LL\Output -m E:/9c1d139d-09a4-452e-87fd-95f81ac5d711/arc/dfv/K1/m/LLK -s 100 -t Original -bs 64 -it 1000000 -g 1 -p -w -v

Stack trace:
Loading...
Traceback (most recent call last):
File "C:\Users\####\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Users\####\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Users\####\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "C:\Users\####\Anaconda3\envs\faceswap\lib\imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "C:\Users\####\Anaconda3\envs\faceswap\lib\imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\####\Downloads\faceswap-master\faceswap-master\faceswap.py", line 36, in <module>
Process exited.ARGUMENTS.func(ARGUMENTS)

File "C:\Users\####\Downloads\faceswap-master\faceswap-master\lib\cli.py", line 79, in execute_script
script = self.import_script()
File "C:\Users\####\Downloads\faceswap-master\faceswap-master\lib\cli.py", line 28, in import_script
module = import_module(mod)
File "C:\Users\####\Anaconda3\envs\faceswap\lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 985, in _gcd_import
File "<frozen importlib._bootstrap>", line 968, in _find_and_load
File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 697, in exec_module
File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
File "C:\Users\####\Downloads\faceswap-master\faceswap-master\scripts\train.py", line 9, in <module>
import tensorflow as tf
File "C:\Users\####\AppData\Roaming\Python\Python35\site-packages\tensorflow\__init__.py", line 24, in <module>
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
File "C:\Users\####\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\__init__.py", line 49, in <module>
from tensorflow.python import pywrap_tensorflow
File "C:\Users\####\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "C:\Users\####\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Users\####\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Users\####\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "C:\Users\####\Anaconda3\envs\faceswap\lib\imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "C:\Users\####\Anaconda3\envs\faceswap\lib\imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Any help would be much appreciated.

**Comment by torzdf** [comment]
CUDA Version, cuDNN version. Tensorflow version.

**Comment by maxsmith2300** [comment]
OS: Windows 10 - 1803
GPU: 1060 6g
Python: 3.5 (via Anaconda3)
CUDA: 9.0.17
cuDNN: 9.0
Tebsorflow: not sure where do I check

Thanks

**Comment by torzdf** [comment]
cudnn won't be 9.0. Make sure it's version 7.0 or 7.1 if using TF 1.12.

You install Tensorflow with:
`pip install <path to tensorflow.whl>`

**Comment by maxsmith2300** [comment]
Sorry, cuDNN is version 7.0.5 for CUDA 9.0
Do I run the "pip install" in the terminal window or somewhere else?

Thanks again

**Comment by maxsmith2300** [comment]
Figured out the install and this was the output

(faceswap) C:\Users\###>pip install https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.12.0-cp35-cp35m-win_amd64.whl
Requirement already satisfied: tensorflow-gpu==1.12.0 from https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.12.0-cp35-cp35m-win_amd64.whl in c:\users\###\appdata\roaming\python\python35\site-packages (1.12.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (1.0.5)
Requirement already satisfied: numpy>=1.13.3 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (1.15.4)
Requirement already satisfied: six>=1.10.0 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (1.11.0)
Requirement already satisfied: keras-applications>=1.0.6 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (1.0.6)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (3.6.1)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (1.1.0)
Requirement already satisfied: gast>=0.2.0 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (0.2.0)
Requirement already satisfied: absl-py>=0.1.6 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (0.6.1)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (1.16.1)
Requirement already satisfied: tensorboard<1.13.0,>=1.12.0 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (1.12.0)
Requirement already satisfied: wheel>=0.26 in c:\users\###\anaconda3\envs\faceswap\lib\site-packages (from tensorflow-gpu==1.12.0) (0.31.1)
Requirement already satisfied: astor>=0.6.0 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorflow-gpu==1.12.0) (0.7.1)
Requirement already satisfied: h5py in c:\users\###\appdata\roaming\python\python35\site-packages (from keras-applications>=1.0.6->tensorflow-gpu==1.12.0) (2.8.0)
Requirement already satisfied: setuptools in c:\users\###\anaconda3\envs\faceswap\lib\site-packages (from protobuf>=3.6.1->tensorflow-gpu==1.12.0) (40.2.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow-gpu==1.12.0) (3.0.1)
Requirement already satisfied: werkzeug>=0.11.10 in c:\users\###\appdata\roaming\python\python35\site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow-gpu==1.12.0) (0.14.1)


Doesn't looks like that was the issue :(

**Comment by torzdf** [comment]
What's your cpu?

**Comment by maxsmith2300** [comment]
AMD Quad core, 3.6ghz

**Comment by torzdf** [comment]
I'd need to know the model type. Basically, there is a chance it doesn't support AVX instructions which means you'd either have to compile TF yourself or download an earlier version.

See here:
https://github.com/tensorflow/tensorflow/issues/17386

**Comment by maxsmith2300** [comment]
It's a AMD Phenom II X4 965, thinking that is going to be the issue. 

Looks like there's a recompiled version 1.6 someone has created. Would that one do the job or would I need to compile/find a newer version?

**Comment by gessyoo** [comment]
maxsmith2300, the AMD Phenom II X4 965 doesn't have AVX or AVX2 instructions.  http://www.cpu-world.com/CPUs/K10/AMD-Phenom%20II%20X4%20965%20Black%20Edition%20-%20HDZ965FBK4DGM%20(HDZ965FBGMBOX).html  So you'd need to compile tensorflow yourself or install a tensorflow python wheel that was compiled with CPU instructions that the Phenom has.
