### ISSUE TITLE
_tkinter.TclError: couldn't recognize data in image file "..../faceswap/lib/gui/.cache/icons/open_folder.png"

### ISSUE THREAD

**Issue by zoeleesss** [deepfakes/faceswap-playground#237]
## Expected behavior

I wanted to open gui, but can't.  
I checked the permissions of the image file or the folder. And even make its permission to 777 , but still doesn't work.

![image](https://user-images.githubusercontent.com/31149915/51166179-95b4bd80-18dd-11e9-9519-8261d2aaa963.png)
![image](https://user-images.githubusercontent.com/31149915/51166273-e1fffd80-18dd-11e9-8b1a-206f7335af0f.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/31149915/51165838-74070680-18dc-11e9-9dbd-e800f15e28b6.png)

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: `python3 faceswap.py gui`
- **Operating system and version:**  macOS
- **Python version:** 3.6.5

* crash report
``` 
01/15/2019 15:40:33 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: TRACE
01/15/2019 15:40:33 MainProcess     MainThread      cli             execute_script            DEBUG    Executing: gui. PID: 5387
01/15/2019 15:40:33 MainProcess     MainThread      __init__        wrapper                   DEBUG    $HOME=/Users/x
01/15/2019 15:40:33 MainProcess     MainThread      __init__        wrapper                   DEBUG    matplotlib data path /usr/local/lib/python3.6/site-packages/matplotlib/mpl-data
01/15/2019 15:40:33 MainProcess     MainThread      __init__        rc_params_from_file       DEBUG    loaded rc file /usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc
01/15/2019 15:40:33 MainProcess     MainThread      __init__        <module>                  DEBUG    matplotlib version 2.2.2
01/15/2019 15:40:33 MainProcess     MainThread      __init__        <module>                  DEBUG    interactive is False
01/15/2019 15:40:33 MainProcess     MainThread      __init__        <module>                  DEBUG    platform is darwin
01/15/2019 15:40:33 MainProcess     MainThread      __init__        <module>                  DEBUG    loaded modules: ['builtins', 'sys', '_frozen_importlib', '_imp', '_warnings', '_thread', '_weakref', '_frozen_importlib_external', '_io', 'marshal', 'posix', 'zipimport', 'encodings', 'codecs', '_codecs', 'encodings.aliases', 'encodings.utf_8', '_signal', '__main__', 'encodings.latin_1', 'io', 'abc', '_weakrefset', 'site', 'os', 'errno', 'stat', '_stat', 'posixpath', 'genericpath', 'os.path', '_collections_abc', '_sitebuiltins', 'sysconfig', '_sysconfigdata_m_darwin_darwin', '_osx_support', 're', 'enum', 'types', 'functools', '_functools', 'collections', 'operator', '_operator', 'keyword', 'heapq', '_heapq', 'itertools', 'reprlib', '_collections', 'weakref', 'collections.abc', 'sre_compile', '_sre', 'sre_parse', 'sre_constants', '_locale', 'copyreg', '_bootlocale', 'importlib', 'importlib._bootstrap', 'importlib._bootstrap_external', 'warnings', 'importlib.util', 'importlib.abc', 'importlib.machinery', 'contextlib', 'mpl_toolkits', 'google', 'sitecustomize', 'encodings.cp437', 'lib', 'lib.cli', 'argparse', 'copy', 'textwrap', 'gettext', 'locale', 'struct', '_struct', 'logging', 'time', 'traceback', 'linecache', 'tokenize', 'token', 'string', '_string', 'threading', 'atexit', 'platform', 'subprocess', 'signal', '_posixsubprocess', 'select', 'selectors', 'math', 'lib.logger', 'logging.handlers', 'socket', '_socket', 'pickle', '_compat_pickle', '_pickle', 'queue', 'datetime', '_datetime', 'lib.queue_manager', 'multiprocessing', 'multiprocessing.context', 'multiprocessing.process', 'multiprocessing.reduction', 'array', '__mp_main__', 'multiprocessing.managers', 'multiprocessing.connection', 'tempfile', 'shutil', 'fnmatch', 'zlib', 'bz2', '_compression', '_bz2', 'lzma', '_lzma', 'pwd', 'grp', 'random', 'hashlib', '_hashlib', '_blake2', '_sha3', 'bisect', '_bisect', '_random', '_multiprocessing', 'multiprocessing.util', 'multiprocessing.pool', 'multiprocessing.popen_fork', 'hmac', 'lib.sysinfo', 'psutil', '__future__', 'psutil._common', 'psutil._compat', 'psutil._exceptions', 'psutil._psosx', 'psutil._psposix', 'glob', 'psutil._psutil_osx', 'psutil._psutil_posix', 'lib.gpu_stats', 'pynvx', 'lib.utils', 'pathlib', 'ntpath', 'urllib', 'urllib.parse', 'cv2', 'numpy', 'numpy._globals', 'numpy.__config__', 'numpy.version', 'numpy._import_tools', 'numpy.add_newdocs', 'numpy.lib', 'numpy.lib.info', 'numpy.lib.type_check', 'numpy.core', 'numpy.core.info', 'numpy.core.multiarray', 'numpy.core.umath', 'numpy.core._internal', 'numpy.compat', 'numpy.compat._inspect', 'numpy.compat.py3k', 'ctypes', '_ctypes', 'ctypes._endian', 'numpy.core.numerictypes', 'numbers', 'numpy.core.numeric', 'numpy.core.fromnumeric', 'numpy.core._methods', 'numpy.core.arrayprint', 'numpy.core.defchararray', 'numpy.core.records', 'numpy.core.memmap', 'numpy.core.function_base', 'numpy.core.machar', 'numpy.core.getlimits', 'numpy.core.shape_base', 'numpy.core.einsumfunc', 'numpy.testing', 'unittest', 'unittest.result', 'unittest.util', 'unittest.case', 'difflib', 'pprint', 'unittest.suite', 'unittest.loader', 'unittest.main', 'unittest.runner', 'unittest.signals', 'numpy.testing._private', 'numpy.testing._private.utils', 'gc', 'numpy.lib.utils', 'numpy.testing._private.decorators', 'numpy.testing._private.nosetester', 'numpy.testing._private.pytesttester', 'numpy.lib.ufunclike', 'numpy.lib.index_tricks', 'numpy.lib.function_base', 'numpy.lib.twodim_base', 'numpy.lib.histograms', 'numpy.matrixlib', 'numpy.matrixlib.defmatrix', 'ast', '_ast', 'numpy.linalg', 'numpy.linalg.info', 'numpy.linalg.linalg', 'numpy.linalg.lapack_lite', 'numpy.linalg._umath_linalg', 'numpy.lib.stride_tricks', 'numpy.lib.mixins', 'numpy.lib.nanfunctions', 'numpy.lib.shape_base', 'numpy.lib.scimath', 'numpy.lib.polynomial', 'numpy.lib.arraysetops', 'numpy.lib.npyio', 'numpy.lib.format', 'numpy.lib._datasource', 'numpy.lib._iotools', 'numpy.lib.financial', 'decimal', '_decimal', 'numpy.lib.arrayterator', 'numpy.lib.arraypad', 'numpy.lib._version', 'numpy.core._multiarray_tests', 'numpy._distributor_init', 'numpy.fft', 'numpy.fft.info', 'numpy.fft.fftpack', 'numpy.fft.fftpack_lite', 'numpy.fft.helper', 'numpy.polynomial', 'numpy.polynomial.polynomial', 'numpy.polynomial.polyutils', 'numpy.polynomial._polybase', 'numpy.polynomial.chebyshev', 'numpy.polynomial.legendre', 'numpy.polynomial.hermite', 'numpy.polynomial.hermite_e', 'numpy.polynomial.laguerre', 'numpy.random', 'numpy.random.info', 'cython_runtime', 'mtrand', 'numpy.random.mtrand', 'numpy.ctypeslib', 'numpy.ma', 'numpy.ma.core', 'numpy.ma.extras', 'cv2.Error', 'cv2.detail', 'cv2.dnn', 'cv2.fisheye', 'cv2.flann', 'cv2.instr', 'cv2.ipp', 'cv2.ml', 'cv2.ocl', 'cv2.ogl', 'cv2.samples', 'cv2.utils', 'cv2.videoio_registry', 'cv2.videostab', 'cv2.cv2', 'cv2.data', 'dlib.cuda', 'dlib.image_dataset_metadata', 'dlib', 'lib.faces_detect', 'lib.aligner', 'lib.umeyama', 'lib.align_eyes', 'lib.training_data', 'lib.multithreading', 'plugins', 'plugins.plugin_loader', 'tkinter', '_tkinter', 'tkinter.constants', 'scripts', 'scripts.gui', 'tkinter.messagebox', 'tkinter.commondialog', 'tkinter.ttk', 'lib.gui', 'lib.gui.command', 'lib.gui.options', 'inspect', 'dis', 'opcode', '_opcode', 'lib.Serializer', 'json', 'json.decoder', 'json.scanner', '_json', 'json.encoder', 'yaml', 'yaml.error', 'yaml.tokens', 'yaml.events', 'yaml.nodes', 'yaml.loader', 'yaml.reader', 'yaml.scanner', 'yaml.parser', 'yaml.composer', 'yaml.constructor', 'base64', 'binascii', 'yaml.resolver', 'yaml.dumper', 'yaml.emitter', 'yaml.serializer', 'yaml.representer', 'tools', 'tools.cli', 'lib.gui.utils', 'tkinter.filedialog', 'tkinter.dialog', 'PIL', 'PIL._version', 'PIL.Image', 'PIL._util', 'PIL._imaging', 'PIL.ImageMode', 'PIL._binary', 'PIL.ImageTk', 'lib.gui.tooltip', 'lib.gui.display', 'lib.gui.display_analysis', 'csv', '_csv', 'lib.gui.display_graph', 'matplotlib', 'six', 'distutils', 'distutils.version', 'distutils.sysconfig', 'distutils.errors', 'matplotlib.cbook', 'six.moves', 'gzip', 'matplotlib.cbook.deprecation', 'matplotlib.cbook._backports', 'matplotlib.compat', 'matplotlib.compat.subprocess', 'matplotlib.rcsetup', 'matplotlib.testing', 'matplotlib.fontconfig_pattern', 'pyparsing', 'matplotlib.colors', 'matplotlib._color_data', 'cycler', 'six.moves.urllib', 'six.moves.urllib.request', 'urllib.request', 'email', 'http', 'http.client', 'email.parser', 'email.feedparser', 'email.errors', 'email._policybase', 'email.header', 'email.quoprimime', 'email.base64mime', 'email.charset', 'email.encoders', 'quopri', 'email.utils', 'email._parseaddr', 'calendar', 'email.message', 'uu', 'email._encoded_words', 'email.iterators', 'ssl', 'ipaddress', '_ssl', 'urllib.error', 'urllib.response', '_scproxy', 'matplotlib._version', 'dateutil', 'dateutil._version']
01/15/2019 15:40:34 MainProcess     MainThread      __init__        wrapper                   DEBUG    CACHEDIR=/Users/x/.matplotlib
01/15/2019 15:40:34 MainProcess     MainThread      font_manager    <module>                  DEBUG    Using fontManager instance from /Users/x/.matplotlib/fontList.json
01/15/2019 15:40:34 MainProcess     MainThread      __init__        pylab_setup               DEBUG    backend TkAgg version unknown
01/15/2019 15:40:34 MainProcess     MainThread      utils           __init__                  DEBUG    Initializing Images: (pathcache: '/Users/x/Documents/GitHub/faceswap/lib/gui/.cache'
Traceback (most recent call last):
  File "/Users/x/Documents/GitHub/faceswap/lib/cli.py", line 89, in execute_script
    process = script(arguments)
  File "/Users/x/Documents/GitHub/faceswap/scripts/gui.py", line 136, in __init__
    self.root = FaceswapGui(pathscript)
  File "/Users/x/Documents/GitHub/faceswap/scripts/gui.py", line 27, in __init__
    self.images = Images(pathcache)
  File "/Users/x/Documents/GitHub/faceswap/lib/gui/utils.py", line 29, in __call__
    **kwargs)
  File "/Users/x/Documents/GitHub/faceswap/lib/gui/utils.py", line 184, in __init__
    "open_folder.png"))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 3542, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 3498, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/Users/x/Documents/GitHub/faceswap/lib/gui/.cache/icons/open_folder.png"


```

**Comment by torzdf** [comment]
Can you enter your faceswap environment and post the output of this command please:
```python -c "import tkinter ; print(tkinter.TkVersion, tkinter.TclVersion)"```

**Comment by torzdf** [comment]
Ok. I'm not sure why this is then. I'm on version 8.6, but that shouldn't make a difference. These looks like a TCL issue rather than a Faceswap issue. Perhaps the image is corrupted? Maybe try to redownload the repo and see if it happens again?

**Comment by zoeleesss** [comment]
@torzdf  So i just downloaded the file, and tried to replace the image file with it. But still doesnt work with same error. So.. am i supposed to upgrade the model tkinter or what?  Any idea?

**Comment by fzred** [comment]
i'm same

**Comment by torzdf** [comment]
This has been fixed in latest commit.
