### ISSUE TITLE
Crash when training with CPU (all branches)

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap-playground#252]
I tried to run faceswap on a muti-cpu machine I have at work and it crashes after just a few iterations :

This machine has 4 * Xeon Gold 6150@2.70GHz (18 cores), so 144 cores/thread  total and 512Gb RAM so it ought to perform reasonably well. but faceswap crashes after a couple iterations.

It's Ubuntu 18.04 and I used the "villain" model with a batch of 16.

Crash report:

```
02/22/2019 16:25:35 MainProcess     training_0      _base           check_loss_drop           DEBUG    Loss for 'a' has not dropped
02/22/2019 16:25:35 MainProcess     training_0      _base           get_save_averages         DEBUG    Lowest historical save iteration loss 

average: {'a'
: 0.2022278606891632, 'b': 0.17215436697006226}
02/22/2019 16:25:35 MainProcess     training_0      _base           get_save_averages         DEBUG    Average loss since last save: {'a': 

0.2191788554191
5894, 'b': 0.1971740424633026}
02/22/2019 16:25:35 MainProcess     training_0      _base           get_save_averages         DEBUG    Backing up: False
02/22/2019 16:25:35 MainProcess     training_0      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 

'save_decoder_a'
, thread_count: 1)
02/22/2019 16:25:35 MainProcess     training_0      multithreading  __init__                  DEBUG    Initialized MultiThread: 'save_decoder_a'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 

'save_decoder_b'
, thread_count: 1)
02/22/2019 16:25:35 MainProcess     training_0      multithreading  __init__                  DEBUG    Initialized MultiThread: 'save_decoder_b'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 

'save_encoder', 
thread_count: 1)
02/22/2019 16:25:35 MainProcess     training_0      multithreading  __init__                  DEBUG    Initialized MultiThread: 'save_encoder'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 

'save_state', th
read_count: 1)
02/22/2019 16:25:35 MainProcess     training_0      multithreading  __init__                  DEBUG    Initialized MultiThread: 'save_state'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Starting thread(s): 'save_decoder_a'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Starting thread 1 of 1: 'save_decoder_a_0'
02/22/2019 16:25:35 MainProcess     save_decoder_a_0 _base           save                      DEBUG    Saving model: 

'/root/models/jodie/villain_decoder_
A.h5'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Started all threads 'save_decoder_a': 1
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Starting thread(s): 'save_decoder_b'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Starting thread 1 of 1: 'save_decoder_b_0'
02/22/2019 16:25:35 MainProcess     save_decoder_b_0 _base           save                      DEBUG    Saving model: 

'/root/models/jodie/villain_decoder_
B.h5'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Started all threads 'save_decoder_b': 1
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Starting thread(s): 'save_encoder'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Starting thread 1 of 1: 'save_encoder_0'
02/22/2019 16:25:35 MainProcess     save_encoder_0  _base           save                      DEBUG    Saving model: 

'/root/models/jodie/villain_encoder.h
5'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Started all threads 'save_encoder': 1
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Starting thread(s): 'save_state'
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Starting thread 1 of 1: 'save_state_0'
02/22/2019 16:25:35 MainProcess     save_state_0    _base           save                      DEBUG    Saving State
02/22/2019 16:25:35 MainProcess     training_0      multithreading  start                     DEBUG    Started all threads 'save_state': 1
02/22/2019 16:25:35 MainProcess     training_0      multithreading  join                      DEBUG    Joining Threads: 'save_decoder_a'
02/22/2019 16:25:35 MainProcess     save_state_0    _base           save                      DEBUG    Saved State
02/22/2019 16:25:35 MainProcess     training_0      multithreading  join                      DEBUG    Joining Thread: 'save_decoder_a_0'
02/22/2019 16:25:41 MainProcess     training_0      multithreading  join                      DEBUG    Joined all Threads: 'save_decoder_a'
02/22/2019 16:25:41 MainProcess     training_0      multithreading  join                      DEBUG    Joining Threads: 'save_decoder_b'
02/22/2019 16:25:41 MainProcess     training_0      multithreading  join                      DEBUG    Joining Thread: 'save_decoder_b_0'
02/22/2019 16:25:41 MainProcess     training_0      multithreading  join                      DEBUG    Joined all Threads: 'save_decoder_b'
02/22/2019 16:25:41 MainProcess     training_0      multithreading  join                      DEBUG    Joining Threads: 'save_encoder'
02/22/2019 16:25:41 MainProcess     training_0      multithreading  join                      DEBUG    Joining Thread: 'save_encoder_0'
02/22/2019 16:25:48 MainProcess     training_0      multithreading  join                      DEBUG    Joined all Threads: 'save_encoder'
02/22/2019 16:25:48 MainProcess     training_0      multithreading  join                      DEBUG    Joining Threads: 'save_state'
02/22/2019 16:25:48 MainProcess     training_0      multithreading  join                      DEBUG    Joining Thread: 'save_state_0'
02/22/2019 16:25:48 MainProcess     training_0      multithreading  join                      DEBUG    Joined all Threads: 'save_state'
02/22/2019 16:25:48 MainProcess     training_0      _base           save_models               INFO     saved models
02/22/2019 16:30:48 MainProcess     training_0      multithreading  run                       DEBUG    Error in thread (training_0): setting an 

array elem
ent with a sequence.
02/22/2019 16:30:48 MainProcess     MainThread      train           monitor_preview           DEBUG    Thread error detected
02/22/2019 16:30:48 MainProcess     MainThread      train           monitor_preview           DEBUG    Closed Preview Monitor
02/22/2019 16:30:48 MainProcess     MainThread      train           end_thread                DEBUG    Ending Training thread
02/22/2019 16:30:48 MainProcess     MainThread      train           end_thread                CRITICAL Error caught! Exiting...
02/22/2019 16:30:48 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: 'training'
02/22/2019 16:30:48 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: 'training_0'
02/22/2019 16:30:48 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: 'training_0'
Traceback (most recent call last):
  File "/root/faceswap/lib/cli.py", line 90, in execute_script
    process.process()
  File "/root/faceswap/scripts/train.py", line 97, in process
    self.end_thread(thread, err)
  File "/root/faceswap/scripts/train.py", line 122, in end_thread
    thread.join()
  File "/root/faceswap/lib/multithreading.py", line 179, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/root/faceswap/lib/multithreading.py", line 117, in run
    self._target(*self._args, **self._kwargs)
  File "/root/faceswap/scripts/train.py", line 148, in training
    raise err
  File "/root/faceswap/scripts/train.py", line 138, in training
    self.run_training_cycle(model, trainer)
  File "/root/faceswap/scripts/train.py", line 210, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "/root/faceswap/plugins/train/trainer/_base.py", line 138, in train_one_step
    loss[side] = batcher.train_one_batch(is_preview_iteration)
  File "/root/faceswap/plugins/train/trainer/_base.py", line 211, in train_one_batch
    batch = self.get_next(is_preview_iteration)
  File "/root/faceswap/plugins/train/trainer/_base.py", line 219, in get_next
    batch = next(self.feed)
  File "/root/faceswap/lib/training_data.py", line 113, in minibatch
    batch = [np.float32(image) for image in batch]
  File "/root/faceswap/lib/training_data.py", line 113, in <listcomp>
    batch = [np.float32(image) for image in batch]
ValueError: setting an array element with a sequence.

============ System Information ============
encoding:          UTF-8
git_branch:        Not Found
git_commits:       Not Found
gpu_cuda:          Not Found
gpu_cudnn:         Not Found
gpu_devices:       
gpu_driver:        No Nvidia driver found
gpu_vram:          
os_machine:        x86_64
os_platform:       Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
os_release:        4.15.0-45-generic
py_command:        /root/faceswap/faceswap.py train -A /root/jodie/aligned -B /root/00_SRC_DATA/aligned -m /root/models/jodie -t villain -s 100 

-bs 16 -it
 1000000 -g 1 -ps 100 -p -L INFO -gui
py_conda_version:  N/A
py_implementation: CPython
py_version:        3.6.7
py_virtual_env:    True
sys_cores:         144
sys_processor:     x86_64
sys_ram:           Total: 515604MB, Available: 496512MB, Used: 16417MB, Free: 487198MB

=============== Pip Packages ===============
absl-py==0.7.0
astor==0.7.1
Click==7.0
cloudpickle==0.8.0
cmake==3.13.3
cycler==0.10.0
dask==1.1.1
decorator==4.3.2
dlib==19.16.0
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.2
grpcio==1.18.0
h5py==2.8.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==2.2.2
networkx==2.2
numpy==1.15.4
nvidia-ml-py3==7.352.0
opencv-python==4.0.0.21
pathlib==1.0.1
Pillow==5.4.1
pkg-resources==0.0.0
protobuf==3.6.1
psutil==5.5.1
pyparsing==2.3.1
python-dateutil==2.8.0
pytz==2018.9
PyWavelets==1.0.1
PyYAML==3.13
scandir==1.7
scikit-image==0.14.2
scikit-learn==0.20.2
scipy==1.2.1
six==1.12.0
tensorboard==1.12.2
tensorflow==1.12.0
termcolor==1.1.0
toolz==0.9.0
tqdm==4.31.1
Werkzeug==0.14.1
```

**Comment by Kirin-kun** [comment]
ValueError: setting an array element with a sequence.

Seems to be the relevant problem?

**Comment by Kirin-kun** [comment]
Back at work this morning, I tested other models and the master branch and I systematically have a crash right when the traning starts:

```
02/25/2019 09:35:58 INFO     Enabled TensorBoard Logging

02/25/2019 09:36:26 INFO     saved models
02/25/2019 09:36:26 CRITICAL Error caught! Exiting...
02/25/2019 09:36:26 ERROR    Caught exception in thread: 'training_0'
02/25/2019 09:36:29 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "/root/faceswap/lib/cli.py", line 90, in execute_script
process.process()
File "/root/faceswap/scripts/train.py", line 97, in process
self.end_thread(thread, err)
File "/root/faceswap/scripts/train.py", line 122, in end_thread
thread.join()
File "/root/faceswap/lib/multithreading.py", line 179, in join
raise thread.err[1].with_traceback(thread.err[2])
File "/root/faceswap/lib/multithreading.py", line 117, in run
self._target(*self._args, **self._kwargs)
File "/root/faceswap/scripts/train.py", line 148, in training
raise err
File "/root/faceswap/scripts/train.py", line 138, in training
self.run_training_cycle(model, trainer)
File "/root/faceswap/scripts/train.py", line 210, in run_training_cycle
trainer.train_one_step(viewer, timelapse)
File "/root/faceswap/plugins/train/trainer/_base.py", line 138, in train_one_step
loss[side] = batcher.train_one_batch(is_preview_iteration)
File "/root/faceswap/plugins/train/trainer/_base.py", line 211, in train_one_batch
batch = self.get_next(is_preview_iteration)
File "/root/faceswap/plugins/train/trainer/_base.py", line 219, in get_next
batch = next(self.feed)
File "/root/faceswap/lib/training_data.py", line 113, in minibatch
batch = [np.float32(image) for image in batch]
File "/root/faceswap/lib/training_data.py", line 113, in <listcomp>
batch = [np.float32(image) for image in batch]
ValueError: setting an array element with a sequence.
02/25/2019 09:36:29 CRITICAL An unexpected crash has occurred. Crash report written to /root/crash_report.2019.02.25.093626761242.log. Please verify you are running the latest version of faceswap before reporting
terminate called without an active exception
Process exited.
```

Conclusion: the CPU mode is useless atm.

It seems there's a bug in the multithreading code,.

**Comment by torzdf** [comment]
@Kirin-kun Can you provide the crash_report please

**Comment by Kirin-kun** [comment]
Here a fresh one with original model selected.  It doesn't even create the model files before crashing.

[crash_report.2019.02.25.122842238872.log](https://github.com/deepfakes/faceswap-playground/files/2900313/crash_report.2019.02.25.122842238872.log)

With "villain" model, it actually takes longer to crash and even create model files and opens a preview window, but it crashes after a minute, with the exact same error: **ValueError: setting an array element with a sequence.**  (see my first post). 

If I re-run it, the preview shows grey squares and then crashes again.

Original model doesn't even start a preview. It crashes immediately.

**Comment by Kirin-kun** [comment]
Crash report with model "villain" and batch size of 16.

It crashes at iteration 6.

[crash_report.2019.02.25.131305286253.log](https://github.com/deepfakes/faceswap-playground/files/2900460/crash_report.2019.02.25.131305286253.log)

It looks like it's crashhing in "multithreading run",

**Comment by torzdf** [comment]
I think this is a RAM issue with Villain model....

It's the only place we have seen this error, and kind of makes sense. If so, then there isn't much we can do about it. You could try lowering the batch size.

If the issue doesn't happen with any of the traditionally 'lower memory' models then we can confirm this is the case and, unfortunately, beyond lowering batchsize, there won't be much we can do.

**Comment by Kirin-kun** [comment]
A RAM issue? with 512Gb of RAM?

**Comment by Kirin-kun** [comment]
And all models, including the original model crashes too. 

I doubt it's a RAM issue.

**Comment by torzdf** [comment]
Ok, that's not good. It's spotty though. Other people are training on CPU, but I will see if I can find out why this is occurring.

**Comment by Kirin-kun** [comment]
Ah. I found why. It's dataset related, not memory related.

In my aligned directory, I had left a face with a 128x128 size, from a previous extraction,  among the 256x256 ones. It looks like finding a different sized face in the set makes it crash when building the batch.

So you were right, it was isolated, 

Not sure it's a bug worth correcting.

**Comment by torzdf** [comment]
Thanks for the update... You saved me a lot of tearing my hair out! I will look to see if we can make it more robust
