### ISSUE TITLE
ImportError: DLL load failed -> I know this issue is quite common but.. please help me out (I may be dumb and missed something)

### ISSUE THREAD

**Issue by tjdwo13579** [deepfakes/faceswap-playground#260]
I have run faceswap in the past successfully but tried updating it now for CUDA v 10.0
So what I did was
1. Delete cuDNN (Can't remember the version) and CUDA v9.0
2. Install CUDA 10.0 and cuDNN v7.4.2
3. Run "python setup.py"
4. Successfully complete the installation
5. Run "faceswap.py -h" -> And get the Error I have written below

So after failing to run the program.. I decided to run from scratch. 
Deleting the existing programs and follow everything depicted on the installation guide.

My Current Environment
OS: Windows 10
CPU: i5-8600K
GPU: GTX 1070
CUDA: 10.0
cuDNN: 7.4.2
CMake: 3.11.0-rc1
Visual Studio 2015 v14.0
Python 3.6.4 64bit

Some other solutions I have tried
1. Restarting my computer (as specified in an issue post here)
2. uninstall current tensorflow and install tf-nightly-gpu -> went back to 1.13.1 after failing

I could try going back to CUDA 9.0 but then my question is.. how much does it effect the performance??

I just don't why I'm unable to run faceswap now, since I'm seeing others are successfully running it with CUDA 10.

## ERROR Message

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Seong Jae Kim\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Seong Jae Kim\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Seong Jae Kim\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Seong Jae Kim\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Seong Jae Kim\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Seong Jae Kim\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Seong Jae Kim\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Games\faceswap\faceswap.py", line 5, in <module>
    import lib.cli as cli
  File "D:\Games\faceswap\lib\cli.py", line 12, in <module>
    from lib.utils import safe_shutdown
  File "D:\Games\faceswap\lib\utils.py", line 15, in <module>
    import dlib
ImportError: DLL load failed: The specified module could not be found.

**Comment by jraspiprojects** [comment]
Run: `pip install https://pypi.python.org/packages/da/06/bd3e241c4eb0a662914b3b4875fc52dd176a9db0d4a2c915ac2ad8800e9e/dlib-19.7.0-cp36-cp36m-win_amd64.whl` in your virtualenv (if you set one up)

**Comment by tjdwo13579** [comment]
@jraspiprojects Thank you! I was able to solve the dlib error with this.
However it did bring up a new issue with numpy (identical to https://github.com/deepfakes/faceswap-playground/issues/261) ... but thanks regardless!
