### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Adam/lr

### ISSUE THREAD

**Issue by wlonglonglong** [deepfakes/faceswap-playground#266]
03/07/2019 17:22:40 INFO     Enabled TensorBoard Logging
03/07/2019 17:39:19 CRITICAL Error caught! Exiting...
03/07/2019 17:39:19 ERROR    Caught exception in thread: 'training_0'
03/07/2019 17:39:21 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "C:\Users\yangyunlong1\faceswap\lib\cli.py", line 107, in execute_script
    process.process()
  File "C:\Users\yangyunlong1\faceswap\scripts\train.py", line 97, in process
    self.end_thread(thread, err)
  File "C:\Users\yangyunlong1\faceswap\scripts\train.py", line 122, in end_thread
    thread.join()
  File "C:\Users\yangyunlong1\faceswap\lib\multithreading.py", line 441, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "C:\Users\yangyunlong1\faceswap\lib\multithreading.py", line 379, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yangyunlong1\faceswap\scripts\train.py", line 148, in training
    raise err
  File "C:\Users\yangyunlong1\faceswap\scripts\train.py", line 138, in training
    self.run_training_cycle(model, trainer)
  File "C:\Users\yangyunlong1\faceswap\scripts\train.py", line 210, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "C:\Users\yangyunlong1\faceswap\plugins\train\trainer\_base.py", line 139, in train_one_step
    loss[side] = batcher.train_one_batch(do_preview)
  File "C:\Users\yangyunlong1\faceswap\plugins\train\trainer\_base.py", line 214, in train_one_batch
    loss = self.model.predictors[self.side].train_on_batch(*batch)
  File "D:\BaiduNetdiskDownload\OpenFaceSwap\OpenFaceSwap\python\python-3.6.3.amd64\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\BaiduNetdiskDownload\OpenFaceSwap\OpenFaceSwap\python\python-3.6.3.amd64\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "D:\BaiduNetdiskDownload\OpenFaceSwap\OpenFaceSwap\python\python-3.6.3.amd64\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "D:\BaiduNetdiskDownload\OpenFaceSwap\OpenFaceSwap\python\python-3.6.3.amd64\lib\site-packages\tensorflow\python\client\session.py", line 1454, in __call__
    self._session._session, self._handle, args, status, None)
  File "D:\BaiduNetdiskDownload\OpenFaceSwap\OpenFaceSwap\python\python-3.6.3.amd64\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Adam/lr
	 [[Node: Adam/lr/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Adam/lr)]]
03/07/2019 17:39:21 CRITICAL An unexpected crash has occurred. Crash report written to C:\Users\yangyunlong1\faceswap\crash_report.2019.03.07.173919459013.log. Please verify you are running the latest version of faceswap before reporting

why this happened? windows 10, tensorflow 1.9.0, Python: 3.6.3 64bit  the latest version of facewap

>

**Comment by wlonglonglong** [comment]
=============== Pip Packages ===============
absl-py==0.7.0
astor==0.7.1
bleach==1.5.0
Brotli==1.0.0
click==6.7
cloudpickle==0.4.1
cmake==3.13.3
cycler==0.10.0
dask==0.15.4
decorator==4.2.1
dlib==19.16.99
docopt==0.6.2
face-alignment==0.1.0
face-recognition==1.2.1
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.2
grpcio==1.19.0
h5py==2.9.0
html5lib==0.9999999
jedi==0.11.0
joblib==0.11
Keras==2.2.4
Keras-Applications==1.0.7
keras-contrib==2.0.8
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
locket==0.2.0
Markdown==3.0.1
matplotlib==2.2.2
networkx==2.1
numpy==1.15.4
nvidia-ml-py3==7.352.0
opencv-python==3.3.0.10
parso==0.1.0
partd==0.3.8
pathlib==1.0.1
Pillow==5.0.0
prompt-toolkit==1.0.15
protobuf==3.6.1
psutil==5.5.1
ptpython==0.41
Pygments==2.2.0
pyodbc==4.0.19
pyparsing==2.2.0
pyreadline==2.0
python-dateutil==2.6.1
python-snappy==0.5.1
pythonnet==2.4.0.dev0
pytz==2018.3
PyWavelets==0.5.2
PyYAML==3.12
scandir==1.6
scikit-image==0.13.1
scikit-learn==0.20.3
scipy==1.0.0
six==1.12.0
sqlite-bro==0.8.11
tensorboard==1.9.0
tensorflow==1.9.0
tensorflow-gpu==1.9.0
tensorflow-tensorboard==1.5.1
termcolor==1.1.0
toolz==0.8.2
tqdm==4.19.6
wcwidth==0.1.7
Werkzeug==0.14.1
winpython==1.9.20171031

**Comment by torzdf** [comment]
Upgrade base code. Upgrade TF to 1.12

**Comment by wlonglonglong** [comment]
> Upgrade base code. Upgrade TF to 1.12

it worked! Thank you!
