### ISSUE TITLE
Number of processes must be at least 1

### ISSUE THREAD

**Issue by martyrzsd** [deepfakes/faceswap-playground#286]
Having troubles when I tried to convert the videos from successfully trained model. After the cv2 DNN is initialized and the loading bar is 0%, it crashed. Saying that

Got Exception on main handler:
Traceback (most recent call last):
  File "/root/faceswap/lib/cli.py", line 110, in execute_script
    process.process()
  File "/root/faceswap/scripts/convert.py", line 95, in process
    self.convert_images()
  File "/root/faceswap/scripts/convert.py", line 110, in convert_images
    processes=self.pool_processes)
  File "/root/faceswap/lib/multithreading.py", line 285, in __init__
    initargs=(logger.getEffectiveLevel(), LOG_QUEUE))
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/multiprocessing/pool.py", line 167, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

[crash_report.2019.05.18.111422912984.log](https://github.com/deepfakes/faceswap-playground/files/3194003/crash_report.2019.05.18.111422912984.log)

I've tried to use the ulimit -a but see nothing wrong.

**Comment by torzdf** [comment]
Should be fixed in latest commit
