### ISSUE TITLE
Crash when using a reference face filter

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap-playground#293]
When extracting a video, I gave a file with a face to extract and it crashes immediately:

Traceback (most recent call last):
  File "C:\Users\Kirin\faceswap\lib\cli.py", line 113, in execute_script
    process = script(arguments)
  File "C:\Users\Kirin\faceswap\scripts\extract.py", line 32, in __init__
    self.post_process = PostProcess(arguments)
  File "C:\Users\Kirin\faceswap\scripts\fsmedia.py", line 242, in __init__
    self.actions = self.set_actions()
  File "C:\Users\Kirin\faceswap\scripts\fsmedia.py", line 247, in set_actions
    postprocess_items = self.get_items()
  File "C:\Users\Kirin\faceswap\scripts\fsmedia.py", line 286, in get_items
    multiprocess=self.args.multiprocess)
AttributeError: 'Namespace' object has no attribute 'multiprocess'

Command line in the gui:

C:\Users\Kirin\faceswap\faceswap.py extract -i C:/Users/Kirin/fan.mp4 -o C:/Fakes/fan/aligned -al C:/Fakes/fan/aligned/alignments.json -l 0.4 -f C:/Fakes/ref/aligned/Fan_000267_0.png --serializer json -D s3fd -A fan -nm clahe -bt 0.0 -sp -sz 256 -min 0 -een 1 -si 0 -L INFO -gui

If I remove the parameter, it proceeds.

Actually, I think this feature has been buggy for a while.

**Comment by torzdf** [comment]
This should be fixed in latest commit (I can't test at the moment, but it's related to a commit that defaults extract to parallel processing a few commits back).

**Comment by Kirin-kun** [comment]
I finally had the time to test, and just after a while, I had an error in the gui:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Python37\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Users\Kirin\faceswap\lib\gui\display_page.py", line 246, in <lambda>
    self.after(waittime, lambda t=waittime: self.update_page(t))
  File "C:\Users\Kirin\faceswap\lib\gui\display_page.py", line 244, in update_page
    self.display_item_set()
  File "C:\Users\Kirin\faceswap\lib\gui\display_command.py", line 28, in display_item_set
    frame_dims=(self.winfo_width(), self.winfo_height()))
  File "C:\Users\Kirin\faceswap\lib\gui\utils.py", line 298, in load_latest_preview
    show_image = self.place_previews(samples, frame_dims)
  File "C:\Users\Kirin\faceswap\lib\gui\utils.py", line 329, in place_previews
    num_images, thumbnail_size = samples.shape[:2]
ValueError: not enough values to unpack (expected 2, got 1)
```
It continued to extract, but the preview of extracted faces was empty. 

Without the reference face, it goes normally.

**Comment by torzdf** [comment]
That's a gui display error. Will check.

**Comment by torzdf** [comment]
@Kirin-kun Is it possible you could run the GUI with trace log enabled (`python faceswap.py gui -L TRACE`). I can't recreate this and I need to discover what is causing this to fail. I thought it may be because it was trying to generate a preview before any files were present, but that should be handled already.

If you enable GUI trace logging, let it run until it fails, and then terminate and provide the log it would be hugely appreciated to be able to track down this bug.

**Comment by Kirin-kun** [comment]
I ran it again with the latest pull, and it didn't happen anymore.

So, I'll close this and reopen if it comes back.

**Comment by torzdf** [comment]
Perfect! Thanks for checking.
