### ISSUE TITLE
Updated FaceSwap crashes upon init

### ISSUE THREAD

**Issue by joestefanik** [deepfakes/faceswap-playground#295]
## Expected behavior

I just updated the client via the GUI after problems with the ffmpeg toolset, and after doing so, I crash upon trying to re-open the program, both via CMD and the GUI (same thing, I guess).
## Actual behavior
Upon calling "python faceswap.py" gui, this is printed:
`06/24/2019 11:04:40 INFO     Log level set to: INFO
06/24/2019 11:04:44 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "C:\Users\XXX\faceswap\lib\cli.py", line 117, in execute_script
    script = self.import_script()
  File "C:\Users\XXX\faceswap\lib\cli.py", line 41, in import_script
    module = import_module(mod)
  File "C:\Users\XXX\MiniConda3\envs\faceswap\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\XXX\faceswap\scripts\gui.py", line 10, in <module>
    from lib.gui import (CliOptions, CommandNotebook, ConsoleOut, Session, DisplayNotebook,
  File "C:\Users\XXX\faceswap\lib\gui\__init__.py", line 9, in <module>
    from lib.gui.wrapper import ProcessWrapper
  File "C:\Users\XXX\faceswap\lib\gui\wrapper.py", line 17, in <module>
    import win32console
ModuleNotFoundError: No module named 'win32console'
06/24/2019 11:04:44 CRITICAL An unexpected crash has occurred. Crash report written to C:\Users\XXX\faceswap\crash_report.2019.06.24.110441945186.log. Please verify you are running the latest version of faceswap before reporting`

I will attatch the crash report to this post.

## Steps to reproduce
The only thing that changed between it working and not working was updating the client.

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)** :python faceswap.py gui
- **Operating system and version:** Windows-10-10.0.18362-SP0
- **Python version:** 3.6.8

[crash_report.2019.06.24.110441945186.log](https://github.com/deepfakes/faceswap-playground/files/3321434/crash_report.2019.06.24.110441945186.log)

**Comment by torzdf** [comment]
You need to install pywin32.

Enter your Faceswap Environment:
`Start > Anaconda Prompt`
```conda activate faceswap```
Then install pywin32:
```conda install pywin32```

Future dependency updates will be handled automatically

**Comment by joestefanik** [comment]
Awesome, fixed!

Thank you!
