### ISSUE TITLE
Previous model files invalid?

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap-playground#301]
My previous model files suddenly became invalid for the villain model (dunno about the other models), I had to retrain from scratch:

```
Traceback (most recent call last):
  File "C:\Users\Kirin\faceswap\lib\cli.py", line 122, in execute_script
    process.process()
  File "C:\Users\Kirin\faceswap\scripts\train.py", line 98, in process
    self.end_thread(thread, err)
  File "C:\Users\Kirin\faceswap\scripts\train.py", line 124, in end_thread
    thread.join()
  File "C:\Users\Kirin\faceswap\lib\multithreading.py", line 460, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "C:\Users\Kirin\faceswap\lib\multithreading.py", line 391, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Kirin\faceswap\scripts\train.py", line 150, in training
    raise err
  File "C:\Users\Kirin\faceswap\scripts\train.py", line 138, in training
    model = self.load_model()
  File "C:\Users\Kirin\faceswap\scripts\train.py", line 173, in load_model
    predict=False)
  File "C:\Users\Kirin\faceswap\plugins\train\model\villain.py", line 25, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Kirin\faceswap\plugins\train\model\original.py", line 25, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Kirin\faceswap\plugins\train\model\_base.py", line 115, in __init__
    self.build()
  File "C:\Users\Kirin\faceswap\plugins\train\model\_base.py", line 205, in build
    self.add_networks()
  File "C:\Users\Kirin\faceswap\plugins\train\model\original.py", line 31, in add_networks
    self.add_network("decoder", "a", self.decoder(), is_output=True)
  File "C:\Users\Kirin\faceswap\plugins\train\model\villain.py", line 69, in decoder
    var_x = self.blocks.res_block(var_x, 512, **kwargs)
  File "C:\Users\Kirin\faceswap\lib\model\nn_blocks.py", line 154, in res_block
    var_x = Add()([var_x, inp])
  File "c:\users\kirin\cface\lib\site-packages\keras\engine\base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "c:\users\kirin\cface\lib\site-packages\keras\layers\merge.py", line 91, in build
    shape)
  File "c:\users\kirin\cface\lib\site-packages\keras\layers\merge.py", line 61, in _compute_elemwise_op_output_shape
    str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (30, 30, 512) (32, 32, 512)
```

Something changed in the model?

**Comment by torzdf** [comment]
Sorry. There was a bug in implementing Convolutional Aware Initialization. This should have been fixed in latest code :/

Your old models will still work.

**Comment by Kirin-kun** [comment]
Models working now.
