### ISSUE TITLE
Analysis not working in latest pull.

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap-playground#303]
OS: Windows 10

I started a fresh new model and the analysis doesn't show up and errors at each refresh:

```
07/26/2019 21:56:16 INFO     [Saved models] - Average since last save: total_loss_A: 0.27090, total_loss_B: 0.28174
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Kirin\faceswap\lib\gui\display_analysis.py", line 99, in load_session
    self.set_session_summary(msg)
  File "C:\Users\Kirin\faceswap\lib\gui\display_analysis.py", line 144, in set_session_summary
    self.summary = self.thread.get_result()
  File "C:\Users\Kirin\faceswap\lib\gui\utils.py", line 1111, in get_result
    raise self.err[1].with_traceback(self.err[2])
  File "C:\Users\Kirin\faceswap\lib\gui\utils.py", line 1090, in run
    retval = self._target(*self._args, **self._kwargs)
  File "C:\Users\Kirin\faceswap\lib\gui\display_analysis.py", line 153, in summarise_data
    return session.full_summary
  File "C:\Users\Kirin\faceswap\lib\gui\stats.py", line 131, in full_summary
    return self.summary.compile_stats()
  File "C:\Users\Kirin\faceswap\lib\gui\stats.py", line 290, in compile_stats
    compiled_stats = self.sessions_stats
  File "C:\Users\Kirin\faceswap\lib\gui\stats.py", line 274, in sessions_stats
    iterations = self.session.get_iterations_for_session(sess_idx)
  File "C:\Users\Kirin\faceswap\lib\gui\stats.py", line 244, in get_iterations_for_session
    session = self.state["sessions"].get(str(session_id), None)
TypeError: 'NoneType' object is not subscriptable
07/26/2019 21:57:21 INFO     Backing up models...
```

**Comment by torzdf** [comment]
This is an inconsistent bug. It is on my list to squash (I'm bugfixing at the moment so hopefully fixed in the next day or 2)

**Comment by Kirin-kun** [comment]
Got a new one:

`08/10/2019 14:11:58 INFO     [Saved models] - Average since last save: total_loss_A: 0.03950, total_loss_B: 0.03023
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Python37\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Users\Kirin\faceswap\lib\gui\display_page.py", line 248, in <lambda>
    self.after(waittime, lambda t=waittime: self.update_page(t))
  File "C:\Users\Kirin\faceswap\lib\gui\display_page.py", line 247, in update_page
    self.load_display()
  File "C:\Users\Kirin\faceswap\lib\gui\display_page.py", line 259, in load_display
    self.display_item_process()
  File "C:\Users\Kirin\faceswap\lib\gui\display_command.py", line 253, in display_item_process
    existing = list(self.subnotebook_get_titles_ids().keys())
  File "C:\Users\Kirin\faceswap\lib\gui\display_page.py", line 138, in subnotebook_get_titles_ids
    for tab_id in range(0, self.subnotebook.index("end")):
  File "C:\Python37\lib\tkinter\ttk.py", line 873, in index
    return self.tk.getint(self.tk.call(self._w, "index", tab_id))
_tkinter.TclError: invalid command name ".!panedwindow.!panedwindow.!displaynotebook.!graphdisplay3.!notebook"

`
I get tkinter errors intermittently when saving in the gui, though it doesn't stop it from training:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Kirin\faceswap\lib\gui\display_analysis.py", line 44, in update_current_session
    self.reset_session()
  File "C:\Users\Kirin\faceswap\lib\gui\display_analysis.py", line 128, in reset_session
    self.set_session_summary(msg)
  File "C:\Users\Kirin\faceswap\lib\gui\display_analysis.py", line 144, in set_session_summary
    self.summary = self.thread.get_result()
  File "C:\Users\Kirin\faceswap\lib\gui\utils.py", line 1111, in get_result
    raise self.err[1].with_traceback(self.err[2])
  File "C:\Users\Kirin\faceswap\lib\gui\utils.py", line 1090, in run
    retval = self._target(*self._args, **self._kwargs)
  File "C:\Users\Kirin\faceswap\lib\gui\display_analysis.py", line 153, in summarise_data
    return session.full_summary
  File "C:\Users\Kirin\faceswap\lib\gui\stats.py", line 131, in full_summary
    return self.summary.compile_stats()
  File "C:\Users\Kirin\faceswap\lib\gui\stats.py", line 290, in compile_stats
    compiled_stats = self.sessions_stats
  File "C:\Users\Kirin\faceswap\lib\gui\stats.py", line 274, in sessions_stats
    iterations = self.session.get_iterations_for_session(sess_idx)
  File "C:\Users\Kirin\faceswap\lib\gui\stats.py", line 244, in get_iterations_for_session
    session = self.state["sessions"].get(str(session_id), None)
TypeError: 'NoneType' object is not subscriptable`

**Comment by torzdf** [comment]
Yeah. I will track these down one day soon. Just haven't prioritized it as it's more annoying than breaking.

Keep up the bug reports though. Keeps me on my toes ;)
