### ISSUE TITLE
Ubuntu 14 install error

### ISSUE THREAD

**Issue by Sugarbank** [deepfakes/faceswap-playground#31]
Any ideas? Thanks:)
(faceswap_env) paperspace@psy21ytam:~/Desktop/SOFTWARE/faceswap-master$ python faceswap.py -hTraceback (most recent call last):
  File "faceswap.py", line 10, in <module>
    from scripts.extract import ExtractTrainingData
  File "/home/paperspace/Desktop/SOFTWARE/faceswap-master/scripts/extract.py", line 4, in <module>
    from lib.cli import DirectoryProcessor
  File "/home/paperspace/Desktop/SOFTWARE/faceswap-master/lib/cli.py", line 7, in <module>
    from lib.FaceFilter import FaceFilter
  File "/home/paperspace/Desktop/SOFTWARE/faceswap-master/lib/FaceFilter.py", line 3, in <module>
    import face_recognition
  File "/home/paperspace/faceswap_env/lib/python3.4/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/paperspace/faceswap_env/lib/python3.4/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
ImportError: /home/paperspace/faceswap_env/lib/python3.4/site-packages/dlib.cpython-34m.so: undefined symbol: dgeqrf_

**Comment by Clorr** [comment]
Hmm strange that you installed dlib and it doesn't work after. Please ensure dlib version is over 19.7.0
