### ISSUE TITLE
Either add Theano to install or remove unecessary import.

### ISSUE THREAD

**Issue by bryanlyon** [deepfakes/faceswap-playground#91]
Traceback (most recent call last):
  File "faceswap.py", line 10, in <module>
    from scripts.extract import ExtractTrainingData
  File "/superm/data/Projects/faceswap/scripts/extract.py", line 7, in <module>
    from lib.cli import DirectoryProcessor
  File "/superm/data/Projects/faceswap/lib/cli.py", line 7, in <module>
    from lib.faces_detect import detect_faces, DetectedFace
  File "/superm/data/Projects/faceswap/lib/faces_detect.py", line 1, in <module>
    from lib import FaceLandmarksExtractor
  File "/superm/data/Projects/faceswap/lib/FaceLandmarksExtractor/__init__.py", line 1, in <module>
    from .FaceLandmarksExtractor import extract
  File "/superm/data/Projects/faceswap/lib/FaceLandmarksExtractor/FaceLandmarksExtractor.py", line 6, in <module>
    import keras
  File "/local/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/local/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/local/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "/local/lib/python3.5/site-packages/keras/backend/__init__.py", line 80, in <module>
    from .theano_backend import *
  File "/home/nikkelitous/.local/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 3, in <module>
    import theano

  File "/usr/local/lib/python3.5/dist-packages/theano/__init__.py", line 88, in <module>
    from theano.configdefaults import config
  File "/usr/local/lib/python3.5/dist-packages/theano/configdefaults.py", line 137, in <module>
    in_c_key=False)
  File "/usr/local/lib/python3.5/dist-packages/theano/configparser.py", line 287, in AddConfigVar
    configparam.__get__(root, type(root), delete_key=True)
  File "/usr/local/lib/python3.5/dist-packages/theano/configparser.py", line 335, in __get__
    self.__set__(cls, val_str)
  File "/usr/local/lib/python3.5/dist-packages/theano/configparser.py", line 346, in __set__
    self.val = self.filter(val)
  File "/usr/local/lib/python3.5/dist-packages/theano/configdefaults.py", line 116, in filter
    'You are tring to use the old GPU back-end. '
ValueError: You are tring to use the old GPU back-end. It was removed from Theano. Use device=cuda* now. See https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29 for more information.

since https://github.com/deepfakes/faceswap/commit/232d9313afabc075e28c1a42047b22e0568200e6 theano is required and will not work with the newest version.

May be specific to Ubuntu Linux but comes from the keras backend being imported in conv_utils.py.

Either we need a supported version added to requirements or find a way to remove the import of keras/backend

**Comment by Clorr** [comment]
Hmm `import backend as K` just loads the configured backend, and the backend is chosen by your own config. Are you sure your [keras backend config](https://keras.io/backend/) is correct?

**Comment by bryanlyon** [comment]
Ahhh, you're right.  In that case, I'd suggest advising people to set their config to tensorflow instead.

**Comment by Clorr** [comment]
Ah ! Nice if you solved your issue. If you have a good way to warn people, fell free to propose, otherwise this issue should help those who have the problem (and take the time to search...)

**Comment by bryanlyon** [comment]
I'd suggest adding the notice into INSTALL.  Since keras defaults (at least on Ubuntu) to Theano, which wont work due to the older version of keras we're using, we should add the notice to the INSTALL.md file.  I can issue a PR if necessary.

**Comment by Clorr** [comment]
Feel free to propose the best solution you are thinking about. If updating keras version can solve this, maybe we can look into this too
